# Generated by Django 4.0.4 on 2023-04-23 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('recipe_image', models.ImageField(blank=True, default='recipes/recipe_default.png', null=True, upload_to='recipes/')),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('serving', models.IntegerField()),
                ('instructions', models.TextField(max_length=5000)),
                ('ingredients', models.TextField(max_length=5000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
