# Generated by Django 4.0.4 on 2023-04-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipes_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
